import './globals.css'
import { Poppins } from 'next/font/google'


const poppins = Poppins({
  weight : ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={poppins.className} >
        <main className="flex h-screen  bg-slate-200 p-2 text-gray-700 selection:bg-neutral-200">
          <nav>je suis la sidebar a gauche</nav>
          <section className="h-full w-full bg-neutral-50 rounded drop-shadow overflow-hidden">
            {children}
          </section>
        </main>
      </body>
    </html>
  )
}
